[build]
buildCommand = "cd bot && npm install --include=dev --package-lock=false --registry=https://registry.npmjs.org && npm run build"

[deploy]
startCommand = "cd bot && npm start"
restartPolicyType = "always"
